# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: league.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import common_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='league.proto',
  package='Dianjing.protocol',
  serialized_pb='\n\x0cleague.proto\x12\x11\x44ianjing.protocol\x1a\x0c\x63ommon.proto\"\x85\x04\n\x06League\x12-\n\x05level\x18\x01 \x02(\x0e\x32\x1e.Dianjing.protocol.LeagueLevel\x12\x15\n\rcurrent_order\x18\x02 \x02(\x05\x12\x33\n\x05ranks\x18\x03 \x03(\x0b\x32$.Dianjing.protocol.League.LeagueRank\x12\x33\n\x05pairs\x18\x04 \x03(\x0b\x32$.Dianjing.protocol.League.LeaguePair\x1aq\n\nLeagueRank\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x0e\n\x06is_npc\x18\x03 \x02(\x08\x12\x14\n\x0c\x62\x61ttle_times\x18\x04 \x02(\x05\x12\r\n\x05score\x18\x05 \x02(\x05\x12\x14\n\x0cwinning_rate\x18\x06 \x02(\x05\x1a\xd7\x01\n\nLeaguePair\x12;\n\x08\x63lub_one\x18\x01 \x02(\x0b\x32).Dianjing.protocol.League.LeaguePair.Club\x12;\n\x08\x63lub_two\x18\x02 \x02(\x0b\x32).Dianjing.protocol.League.LeaguePair.Club\x12\x10\n\x08start_at\x18\x03 \x02(\x05\x1a=\n\x04\x43lub\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x0e\n\x06is_npc\x18\x03 \x02(\x08\x12\x0b\n\x03win\x18\x04 \x02(\x08\"J\n\x0cLeagueNotify\x12\x0f\n\x07session\x18\x01 \x02(\x0c\x12)\n\x06league\x18\x02 \x02(\x0b\x32\x19.Dianjing.protocol.League')




_LEAGUE_LEAGUERANK = _descriptor.Descriptor(
  name='LeagueRank',
  full_name='Dianjing.protocol.League.LeagueRank',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Dianjing.protocol.League.LeagueRank.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='Dianjing.protocol.League.LeagueRank.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_npc', full_name='Dianjing.protocol.League.LeagueRank.is_npc', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='battle_times', full_name='Dianjing.protocol.League.LeagueRank.battle_times', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='score', full_name='Dianjing.protocol.League.LeagueRank.score', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='winning_rate', full_name='Dianjing.protocol.League.LeagueRank.winning_rate', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=236,
  serialized_end=349,
)

_LEAGUE_LEAGUEPAIR_CLUB = _descriptor.Descriptor(
  name='Club',
  full_name='Dianjing.protocol.League.LeaguePair.Club',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Dianjing.protocol.League.LeaguePair.Club.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='Dianjing.protocol.League.LeaguePair.Club.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_npc', full_name='Dianjing.protocol.League.LeaguePair.Club.is_npc', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='win', full_name='Dianjing.protocol.League.LeaguePair.Club.win', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=506,
  serialized_end=567,
)

_LEAGUE_LEAGUEPAIR = _descriptor.Descriptor(
  name='LeaguePair',
  full_name='Dianjing.protocol.League.LeaguePair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='club_one', full_name='Dianjing.protocol.League.LeaguePair.club_one', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='club_two', full_name='Dianjing.protocol.League.LeaguePair.club_two', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_at', full_name='Dianjing.protocol.League.LeaguePair.start_at', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_LEAGUE_LEAGUEPAIR_CLUB, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=352,
  serialized_end=567,
)

_LEAGUE = _descriptor.Descriptor(
  name='League',
  full_name='Dianjing.protocol.League',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='level', full_name='Dianjing.protocol.League.level', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='current_order', full_name='Dianjing.protocol.League.current_order', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ranks', full_name='Dianjing.protocol.League.ranks', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pairs', full_name='Dianjing.protocol.League.pairs', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_LEAGUE_LEAGUERANK, _LEAGUE_LEAGUEPAIR, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=50,
  serialized_end=567,
)


_LEAGUENOTIFY = _descriptor.Descriptor(
  name='LeagueNotify',
  full_name='Dianjing.protocol.LeagueNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='Dianjing.protocol.LeagueNotify.session', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='league', full_name='Dianjing.protocol.LeagueNotify.league', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=569,
  serialized_end=643,
)

_LEAGUE_LEAGUERANK.containing_type = _LEAGUE;
_LEAGUE_LEAGUEPAIR_CLUB.containing_type = _LEAGUE_LEAGUEPAIR;
_LEAGUE_LEAGUEPAIR.fields_by_name['club_one'].message_type = _LEAGUE_LEAGUEPAIR_CLUB
_LEAGUE_LEAGUEPAIR.fields_by_name['club_two'].message_type = _LEAGUE_LEAGUEPAIR_CLUB
_LEAGUE_LEAGUEPAIR.containing_type = _LEAGUE;
_LEAGUE.fields_by_name['level'].enum_type = common_pb2._LEAGUELEVEL
_LEAGUE.fields_by_name['ranks'].message_type = _LEAGUE_LEAGUERANK
_LEAGUE.fields_by_name['pairs'].message_type = _LEAGUE_LEAGUEPAIR
_LEAGUENOTIFY.fields_by_name['league'].message_type = _LEAGUE
DESCRIPTOR.message_types_by_name['League'] = _LEAGUE
DESCRIPTOR.message_types_by_name['LeagueNotify'] = _LEAGUENOTIFY

class League(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class LeagueRank(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _LEAGUE_LEAGUERANK

    # @@protoc_insertion_point(class_scope:Dianjing.protocol.League.LeagueRank)

  class LeaguePair(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType

    class Club(_message.Message):
      __metaclass__ = _reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _LEAGUE_LEAGUEPAIR_CLUB

      # @@protoc_insertion_point(class_scope:Dianjing.protocol.League.LeaguePair.Club)
    DESCRIPTOR = _LEAGUE_LEAGUEPAIR

    # @@protoc_insertion_point(class_scope:Dianjing.protocol.League.LeaguePair)
  DESCRIPTOR = _LEAGUE

  # @@protoc_insertion_point(class_scope:Dianjing.protocol.League)

class LeagueNotify(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LEAGUENOTIFY

  # @@protoc_insertion_point(class_scope:Dianjing.protocol.LeagueNotify)


# @@protoc_insertion_point(module_scope)
