# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: package.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='package.proto',
  package='Dianjing.protocol',
  syntax='proto2',
  serialized_pb=b'\n\rpackage.proto\x12\x11\x44ianjing.protocol\".\n\x08Resource\x12\x13\n\x0bresource_id\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\x05\"\x95\x01\n\x04\x44rop\x12.\n\tresources\x18\x01 \x03(\x0b\x32\x1b.Dianjing.protocol.Resource\x12\x34\n\ttrainings\x18\x02 \x03(\x0b\x32!.Dianjing.protocol.Drop.Trainings\x1a\'\n\tTrainings\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x02(\x05\"\xa8\x01\n\x0cTrainingItem\x12.\n\tresources\x18\x01 \x03(\x0b\x32\x1b.Dianjing.protocol.Resource\x12<\n\x05skill\x18\x02 \x01(\x0b\x32-.Dianjing.protocol.TrainingItem.TrainingSkill\x1a*\n\rTrainingSkill\x12\n\n\x02id\x18\x01 \x02(\x05\x12\r\n\x05level\x18\x02 \x02(\x05'
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RESOURCE = _descriptor.Descriptor(
  name='Resource',
  full_name='Dianjing.protocol.Resource',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resource_id', full_name='Dianjing.protocol.Resource.resource_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='Dianjing.protocol.Resource.value', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=82,
)


_DROP_TRAININGS = _descriptor.Descriptor(
  name='Trainings',
  full_name='Dianjing.protocol.Drop.Trainings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Dianjing.protocol.Drop.Trainings.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amount', full_name='Dianjing.protocol.Drop.Trainings.amount', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=234,
)

_DROP = _descriptor.Descriptor(
  name='Drop',
  full_name='Dianjing.protocol.Drop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resources', full_name='Dianjing.protocol.Drop.resources', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trainings', full_name='Dianjing.protocol.Drop.trainings', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DROP_TRAININGS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=234,
)


_TRAININGITEM_TRAININGSKILL = _descriptor.Descriptor(
  name='TrainingSkill',
  full_name='Dianjing.protocol.TrainingItem.TrainingSkill',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Dianjing.protocol.TrainingItem.TrainingSkill.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='Dianjing.protocol.TrainingItem.TrainingSkill.level', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=363,
  serialized_end=405,
)

_TRAININGITEM = _descriptor.Descriptor(
  name='TrainingItem',
  full_name='Dianjing.protocol.TrainingItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resources', full_name='Dianjing.protocol.TrainingItem.resources', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skill', full_name='Dianjing.protocol.TrainingItem.skill', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TRAININGITEM_TRAININGSKILL, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=405,
)

_DROP_TRAININGS.containing_type = _DROP
_DROP.fields_by_name['resources'].message_type = _RESOURCE
_DROP.fields_by_name['trainings'].message_type = _DROP_TRAININGS
_TRAININGITEM_TRAININGSKILL.containing_type = _TRAININGITEM
_TRAININGITEM.fields_by_name['resources'].message_type = _RESOURCE
_TRAININGITEM.fields_by_name['skill'].message_type = _TRAININGITEM_TRAININGSKILL
DESCRIPTOR.message_types_by_name['Resource'] = _RESOURCE
DESCRIPTOR.message_types_by_name['Drop'] = _DROP
DESCRIPTOR.message_types_by_name['TrainingItem'] = _TRAININGITEM

Resource = _reflection.GeneratedProtocolMessageType('Resource', (_message.Message,), dict(
  DESCRIPTOR = _RESOURCE,
  __module__ = 'package_pb2'
  # @@protoc_insertion_point(class_scope:Dianjing.protocol.Resource)
  ))
_sym_db.RegisterMessage(Resource)

Drop = _reflection.GeneratedProtocolMessageType('Drop', (_message.Message,), dict(

  Trainings = _reflection.GeneratedProtocolMessageType('Trainings', (_message.Message,), dict(
    DESCRIPTOR = _DROP_TRAININGS,
    __module__ = 'package_pb2'
    # @@protoc_insertion_point(class_scope:Dianjing.protocol.Drop.Trainings)
    ))
  ,
  DESCRIPTOR = _DROP,
  __module__ = 'package_pb2'
  # @@protoc_insertion_point(class_scope:Dianjing.protocol.Drop)
  ))
_sym_db.RegisterMessage(Drop)
_sym_db.RegisterMessage(Drop.Trainings)

TrainingItem = _reflection.GeneratedProtocolMessageType('TrainingItem', (_message.Message,), dict(

  TrainingSkill = _reflection.GeneratedProtocolMessageType('TrainingSkill', (_message.Message,), dict(
    DESCRIPTOR = _TRAININGITEM_TRAININGSKILL,
    __module__ = 'package_pb2'
    # @@protoc_insertion_point(class_scope:Dianjing.protocol.TrainingItem.TrainingSkill)
    ))
  ,
  DESCRIPTOR = _TRAININGITEM,
  __module__ = 'package_pb2'
  # @@protoc_insertion_point(class_scope:Dianjing.protocol.TrainingItem)
  ))
_sym_db.RegisterMessage(TrainingItem)
_sym_db.RegisterMessage(TrainingItem.TrainingSkill)


# @@protoc_insertion_point(module_scope)
