# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: purchase.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='purchase.proto',
  package='Dianjing.protocol',
  syntax='proto2',
  serialized_pb=_b('\n\x0epurchase.proto\x12\x11\x44ianjing.protocol\"M\n\x0ePurchaseNotify\x12\x0f\n\x07session\x18\x01 \x02(\x0c\x12\x1b\n\x13yueka_remained_days\x18\x02 \x02(\x05\x12\r\n\x05\x66irst\x18\x03 \x02(\x08\";\n\x16PurchasePrepareRequest\x12\x0f\n\x07session\x18\x01 \x02(\x0c\x12\x10\n\x08goods_id\x18\x02 \x02(\x05\"H\n\x17PurchasePrepareResponse\x12\x0b\n\x03ret\x18\x01 \x02(\x05\x12\x0f\n\x07session\x18\x02 \x02(\x0c\x12\x0f\n\x07receipt\x18\x03 \x01(\t\"9\n\x15PurchaseVerifyRequest\x12\x0f\n\x07session\x18\x01 \x02(\x0c\x12\x0f\n\x07receipt\x18\x02 \x02(\t\"{\n\x16PurchaseVerifyResponse\x12\x0b\n\x03ret\x18\x01 \x02(\x05\x12\x0f\n\x07session\x18\x02 \x02(\x0c\x12\x31\n\x06status\x18\x03 \x01(\x0e\x32!.Dianjing.protocol.PurchaseStatus\x12\x10\n\x08goods_id\x18\x04 \x01(\x05*O\n\x0ePurchaseStatus\x12\x11\n\rPURCHASE_DONE\x10\x01\x12\x14\n\x10PURCHASE_WAITING\x10\x02\x12\x14\n\x10PURCHASE_FAILURE\x10\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_PURCHASESTATUS = _descriptor.EnumDescriptor(
  name='PurchaseStatus',
  full_name='Dianjing.protocol.PurchaseStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PURCHASE_DONE', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PURCHASE_WAITING', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PURCHASE_FAILURE', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=435,
  serialized_end=514,
)
_sym_db.RegisterEnumDescriptor(_PURCHASESTATUS)

PurchaseStatus = enum_type_wrapper.EnumTypeWrapper(_PURCHASESTATUS)
PURCHASE_DONE = 1
PURCHASE_WAITING = 2
PURCHASE_FAILURE = 3



_PURCHASENOTIFY = _descriptor.Descriptor(
  name='PurchaseNotify',
  full_name='Dianjing.protocol.PurchaseNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='Dianjing.protocol.PurchaseNotify.session', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yueka_remained_days', full_name='Dianjing.protocol.PurchaseNotify.yueka_remained_days', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='first', full_name='Dianjing.protocol.PurchaseNotify.first', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=114,
)


_PURCHASEPREPAREREQUEST = _descriptor.Descriptor(
  name='PurchasePrepareRequest',
  full_name='Dianjing.protocol.PurchasePrepareRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='Dianjing.protocol.PurchasePrepareRequest.session', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='goods_id', full_name='Dianjing.protocol.PurchasePrepareRequest.goods_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=175,
)


_PURCHASEPREPARERESPONSE = _descriptor.Descriptor(
  name='PurchasePrepareResponse',
  full_name='Dianjing.protocol.PurchasePrepareResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='Dianjing.protocol.PurchasePrepareResponse.ret', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='session', full_name='Dianjing.protocol.PurchasePrepareResponse.session', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='receipt', full_name='Dianjing.protocol.PurchasePrepareResponse.receipt', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=249,
)


_PURCHASEVERIFYREQUEST = _descriptor.Descriptor(
  name='PurchaseVerifyRequest',
  full_name='Dianjing.protocol.PurchaseVerifyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='Dianjing.protocol.PurchaseVerifyRequest.session', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='receipt', full_name='Dianjing.protocol.PurchaseVerifyRequest.receipt', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=308,
)


_PURCHASEVERIFYRESPONSE = _descriptor.Descriptor(
  name='PurchaseVerifyResponse',
  full_name='Dianjing.protocol.PurchaseVerifyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='Dianjing.protocol.PurchaseVerifyResponse.ret', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='session', full_name='Dianjing.protocol.PurchaseVerifyResponse.session', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='Dianjing.protocol.PurchaseVerifyResponse.status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='goods_id', full_name='Dianjing.protocol.PurchaseVerifyResponse.goods_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=433,
)

_PURCHASEVERIFYRESPONSE.fields_by_name['status'].enum_type = _PURCHASESTATUS
DESCRIPTOR.message_types_by_name['PurchaseNotify'] = _PURCHASENOTIFY
DESCRIPTOR.message_types_by_name['PurchasePrepareRequest'] = _PURCHASEPREPAREREQUEST
DESCRIPTOR.message_types_by_name['PurchasePrepareResponse'] = _PURCHASEPREPARERESPONSE
DESCRIPTOR.message_types_by_name['PurchaseVerifyRequest'] = _PURCHASEVERIFYREQUEST
DESCRIPTOR.message_types_by_name['PurchaseVerifyResponse'] = _PURCHASEVERIFYRESPONSE
DESCRIPTOR.enum_types_by_name['PurchaseStatus'] = _PURCHASESTATUS

PurchaseNotify = _reflection.GeneratedProtocolMessageType('PurchaseNotify', (_message.Message,), dict(
  DESCRIPTOR = _PURCHASENOTIFY,
  __module__ = 'purchase_pb2'
  # @@protoc_insertion_point(class_scope:Dianjing.protocol.PurchaseNotify)
  ))
_sym_db.RegisterMessage(PurchaseNotify)

PurchasePrepareRequest = _reflection.GeneratedProtocolMessageType('PurchasePrepareRequest', (_message.Message,), dict(
  DESCRIPTOR = _PURCHASEPREPAREREQUEST,
  __module__ = 'purchase_pb2'
  # @@protoc_insertion_point(class_scope:Dianjing.protocol.PurchasePrepareRequest)
  ))
_sym_db.RegisterMessage(PurchasePrepareRequest)

PurchasePrepareResponse = _reflection.GeneratedProtocolMessageType('PurchasePrepareResponse', (_message.Message,), dict(
  DESCRIPTOR = _PURCHASEPREPARERESPONSE,
  __module__ = 'purchase_pb2'
  # @@protoc_insertion_point(class_scope:Dianjing.protocol.PurchasePrepareResponse)
  ))
_sym_db.RegisterMessage(PurchasePrepareResponse)

PurchaseVerifyRequest = _reflection.GeneratedProtocolMessageType('PurchaseVerifyRequest', (_message.Message,), dict(
  DESCRIPTOR = _PURCHASEVERIFYREQUEST,
  __module__ = 'purchase_pb2'
  # @@protoc_insertion_point(class_scope:Dianjing.protocol.PurchaseVerifyRequest)
  ))
_sym_db.RegisterMessage(PurchaseVerifyRequest)

PurchaseVerifyResponse = _reflection.GeneratedProtocolMessageType('PurchaseVerifyResponse', (_message.Message,), dict(
  DESCRIPTOR = _PURCHASEVERIFYRESPONSE,
  __module__ = 'purchase_pb2'
  # @@protoc_insertion_point(class_scope:Dianjing.protocol.PurchaseVerifyResponse)
  ))
_sym_db.RegisterMessage(PurchaseVerifyResponse)


# @@protoc_insertion_point(module_scope)
