# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resource.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='resource.proto',
  package='Dianjing.protocol',
  syntax='proto2',
  serialized_pb=_b('\n\x0eresource.proto\x12\x11\x44ianjing.protocol\"\x87\x01\n\x0eResourceNotify\x12\x0f\n\x07session\x18\x01 \x02(\x0c\x12<\n\x08resource\x18\x02 \x03(\x0b\x32*.Dianjing.protocol.ResourceNotify.Resource\x1a&\n\x08Resource\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RESOURCENOTIFY_RESOURCE = _descriptor.Descriptor(
  name='Resource',
  full_name='Dianjing.protocol.ResourceNotify.Resource',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Dianjing.protocol.ResourceNotify.Resource.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amount', full_name='Dianjing.protocol.ResourceNotify.Resource.amount', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=173,
)

_RESOURCENOTIFY = _descriptor.Descriptor(
  name='ResourceNotify',
  full_name='Dianjing.protocol.ResourceNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='Dianjing.protocol.ResourceNotify.session', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resource', full_name='Dianjing.protocol.ResourceNotify.resource', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_RESOURCENOTIFY_RESOURCE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=173,
)

_RESOURCENOTIFY_RESOURCE.containing_type = _RESOURCENOTIFY
_RESOURCENOTIFY.fields_by_name['resource'].message_type = _RESOURCENOTIFY_RESOURCE
DESCRIPTOR.message_types_by_name['ResourceNotify'] = _RESOURCENOTIFY

ResourceNotify = _reflection.GeneratedProtocolMessageType('ResourceNotify', (_message.Message,), dict(

  Resource = _reflection.GeneratedProtocolMessageType('Resource', (_message.Message,), dict(
    DESCRIPTOR = _RESOURCENOTIFY_RESOURCE,
    __module__ = 'resource_pb2'
    # @@protoc_insertion_point(class_scope:Dianjing.protocol.ResourceNotify.Resource)
    ))
  ,
  DESCRIPTOR = _RESOURCENOTIFY,
  __module__ = 'resource_pb2'
  # @@protoc_insertion_point(class_scope:Dianjing.protocol.ResourceNotify)
  ))
_sym_db.RegisterMessage(ResourceNotify)
_sym_db.RegisterMessage(ResourceNotify.Resource)


# @@protoc_insertion_point(module_scope)
