# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('server_id', models.IntegerField()),
                ('name', models.CharField(db_index=True, max_length=32)),
                ('create_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_login', models.DateTimeField(auto_now=True, db_index=True)),
                ('login_times', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ('-last_login',),
                'db_table': 'char_',
                'verbose_name': '\u89d2\u8272(\u4ff1\u4e50\u90e8)',
                'verbose_name_plural': '\u89d2\u8272(\u4ff1\u4e50\u90e8)',
            },
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together=set([('server_id', 'name'), ('account_id', 'server_id')]),
        ),
    ]
