# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForbidChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_id', models.IntegerField(db_index=True)),
                ('reason', models.TextField(blank=True)),
                ('unforbidden_at', models.DateTimeField(db_index=True, verbose_name=b'\xe8\xa7\xa3\xe9\x99\xa4\xe6\x97\xb6\xe9\x97\xb4')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-id',),
                'db_table': 'forbid_chat',
                'verbose_name': '\u7981\u6b62\u804a\u5929',
                'verbose_name_plural': '\u7981\u6b62\u804a\u5929',
            },
        ),
    ]
