# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-29 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_auto_20151125_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ('-last_login',), 'verbose_name': '\u89d2\u8272(\u4ff1\u4e50\u90e8)', 'verbose_name_plural': '\u89d2\u8272(\u4ff1\u4e50\u90e8)'},
        ),
        migrations.RemoveField(
            model_name='character',
            name='avatar_key',
        ),
        migrations.RemoveField(
            model_name='character',
            name='avatar_ok',
        ),
        migrations.RemoveField(
            model_name='character',
            name='club_name',
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together=set([('server_id', 'name'), ('account_id', 'server_id')]),
        ),
    ]
