# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20150915_1233'),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS bulletin;"),
        migrations.RunSQL("DROP TABLE IF EXISTS broadcast;"),
    ]
