# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 07:55
from __future__ import unicode_literals

import apps.config.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_auto_20160810_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name=b'\xe5\x86\x85\xe5\xae\xb9')),
                ('repeat_times', models.IntegerField(default=0, help_text=b'0\xe8\xa1\xa8\xe7\xa4\xba\xe4\xb8\x80\xe7\x9b\xb4\xe9\x87\x8d\xe5\xa4\x8d', verbose_name=b'\xe9\x87\x8d\xe5\xa4\x8d\xe6\xac\xa1\xe6\x95\xb0')),
                ('display', models.BooleanField(db_index=True, default=True, verbose_name=b'\xe6\x98\xbe\xe7\xa4\xba')),
            ],
            options={
                'db_table': 'broadcast',
                'verbose_name': '\u8d70\u9a6c\u706f',
                'verbose_name_plural': '\u8d70\u9a6c\u706f',
            },
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('content', models.TextField(blank=True, verbose_name=b'\xe5\x86\x85\xe5\xae\xb9')),
                ('image', models.FileField(blank=True, null=True, upload_to=apps.config.models.image_upload_to, verbose_name=b'\xe5\x9b\xbe\xe7\x89\x87')),
                ('order_num', models.IntegerField(db_index=True, default=1, help_text=b'\xe6\x95\xb0\xe5\xad\x97\xe8\xb6\x8a\xe5\xa4\xa7\xe8\xb6\x8a\xe9\x9d\xa0\xe5\x89\x8d', verbose_name=b'\xe6\x8e\x92\xe5\x88\x97\xe5\xba\x8f\xe5\x8f\xb7')),
                ('display', models.BooleanField(db_index=True, default=True, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe6\x98\xbe\xe7\xa4\xba')),
            ],
            options={
                'db_table': 'bulletin',
                'verbose_name': '\u516c\u544a',
                'verbose_name_plural': '\u516c\u544a',
            },
        ),
    ]
