# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_broadcast_bulletin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerserviceinformation',
            options={'verbose_name': '\u81ea\u5b9a\u4e49\u4fe1\u606f', 'verbose_name_plural': '\u81ea\u5b9a\u4e49\u4fe1\u606f'},
        ),
    ]
