# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 09:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_auto_20161020_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('content', models.TextField(verbose_name=b'\xe5\x86\x85\xe5\xae\xb9')),
                ('items', models.TextField(blank=True, verbose_name=b'\xe9\x99\x84\xe4\xbb\xb6')),
                ('send_at', models.DateTimeField(db_index=True, verbose_name=b'\xe5\x8f\x91\xe9\x80\x81\xe6\x97\xb6\xe9\x97\xb4')),
                ('condition_type', models.IntegerField(choices=[(1, b'\xe5\x85\xa8\xe9\x83\xa8\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8'), (2, b'\xe6\x8c\x87\xe5\xae\x9a\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8'), (3, b'\xe6\x8e\x92\xe9\x99\xa4\xe6\x8c\x87\xe5\xae\x9a\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8'), (11, b'\xe6\x8c\x87\xe5\xae\x9a\xe8\xa7\x92\xe8\x89\xb2ID')], verbose_name=b'\xe5\x8f\x91\xe9\x80\x81\xe6\x9d\xa1\xe4\xbb\xb6')),
                ('condition_value', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name=b'\xe6\x9d\xa1\xe4\xbb\xb6\xe5\x80\xbcID\xe5\x88\x97\xe8\xa1\xa8')),
                ('condition_club_level', models.PositiveIntegerField(blank=True, null=True, verbose_name=b'\xe4\xbf\xb1\xe4\xb9\x90\xe9\x83\xa8\xe7\xad\x89\xe7\xba\xa7\xe5\xa4\xa7\xe4\xba\x8e\xe7\xad\x89\xe4\xba\x8e')),
                ('condition_vip_level', models.PositiveIntegerField(blank=True, null=True, verbose_name=b'VIP\xe7\xad\x89\xe7\xba\xa7\xe5\xa4\xa7\xe4\xba\x8e\xe7\xad\x89\xe4\xba\x8e')),
                ('condition_login_at_1', models.DateTimeField(blank=True, null=True, verbose_name=b'\xe7\x99\xbb\xe9\x99\x86\xe6\x97\xb6\xe9\x97\xb4\xe5\xa4\xa7\xe4\xba\x8e\xe7\xad\x89\xe4\xba\x8e')),
                ('condition_login_at_2', models.DateTimeField(blank=True, null=True, verbose_name=b'\xe7\x99\xbb\xe9\x99\x86\xe6\x97\xb6\xe9\x97\xb4\xe5\xb0\x8f\xe4\xba\x8e\xe7\xad\x89\xe4\xba\x8e')),
                ('condition_exclude_chars', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name=b'\xe6\x8e\x92\xe9\x99\xa4\xe8\xa7\x92\xe8\x89\xb2ID\xe5\x88\x97\xe8\xa1\xa8')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('status', models.IntegerField(choices=[(0, b'\xe7\xad\x89\xe5\xbe\x85'), (1, b'\xe6\xad\xa3\xe5\x9c\xa8\xe5\x8f\x91\xe9\x80\x81'), (2, b'\xe5\xae\x8c\xe6\x88\x90'), (3, b'\xe5\xa4\xb1\xe8\xb4\xa5')], db_index=True, default=0, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
            ],
            options={
                'db_table': 'mail',
                'verbose_name': '\u90ae\u4ef6',
                'verbose_name_plural': '\u90ae\u4ef6',
            },
        ),
    ]
