# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 07:47
from __future__ import unicode_literals

import apps.config.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='client_config',
            field=models.FileField(default='', upload_to=apps.config.models.client_config_upload_to, verbose_name=b'\xe5\xae\xa2\xe6\x88\xb7\xe7\xab\xaf\xe9\x85\x8d\xe7\xbd\xae'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='config',
            name='config',
            field=models.FileField(upload_to=apps.config.models.config_upload_to, verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8\xe9\x85\x8d\xe7\xbd\xae'),
        ),
    ]
