# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='mongo_db',
        ),
        migrations.RemoveField(
            model_name='server',
            name='mongo_host',
        ),
        migrations.RemoveField(
            model_name='server',
            name='mongo_port',
        ),
    ]
