# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20161011_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.IntegerField(choices=[(1, b'\xe6\xad\xa3\xe5\xb8\xb8'), (2, b'\xe7\x81\xab\xe7\x88\x86'), (3, b'\xe7\xbb\xb4\xe6\x8a\xa4')], default=1),
        ),
    ]
