# -*- coding: utf-8 -*-
"""
Author:         Wang Chao <yueyoum@gmail.com>
Filename:       settings
Date Created:   2015-07-22 16:25
Description:

"""

CHAR_INIT_GOLD = 100000
CHAR_INIT_DIAMOND = 0
CHAR_INIT_STAFFS = [2, 3, 4, 5, 134]

# 俱乐部买员工格子花费钻石
BUY_STAFF_SLOT_COST = 50


CHAR_NAME_MAX_LENGTH = 7

LEAGUE_START_TIME_ONE = "12:00:00+08:00"
LEAGUE_START_TIME_TWO = "20:00:00+08:00"

MAIL_CLEAN_AT = "03:00:00+08:00"
MAIL_KEEP_DAYS = 7

# 通知条数
NOTIFICATION_MAX_AMOUNT = 20


# 联赛
LEAGUE_DAY_WIN_MAIL_TITLE = u"联赛赢了"
LEAGUE_DAY_WIN_MAIL_CONTENT = u"联赛赢了"
LEAGUE_DAY_LOSE_MAIL_TITLE = u"联赛输了"
LEAGUE_DAY_LOSE_MAIL_CONTENT = u"联赛输了"

LEAGUE_WEEK_MAIL_TITLE = u"联赛周奖励"
LEAGUE_WEEK_MAIL_CONTENT = u"联赛周奖励"

LEAGUE_WIN_SCORE = 3
LEAGUE_LOSE_SCORE = 1

# 天梯
LADDER_NPC_AMOUNT = 2000
LADDER_DEFAULT_MATCH_TIMES = 10
LADDER_LOG_MAX_AMOUNT = 20
LADDER_MAX_SCORE = 1000000

# 好友
FRIEND_CANDIDATES_AMOUNT = 8
