# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20150918_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountthird',
            name='provider',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='accountthird',
            unique_together=set([('provider', 'platform', 'uid')]),
        ),
    ]
