# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20170117_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeTuiClientID',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'getui_clientid',
                'verbose_name': '\u4e2a\u63a8clientid',
                'verbose_name_plural': '\u4e2a\u63a8clientid',
            },
        ),
    ]
