# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCode',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('items', models.TextField()),
                ('times_limit', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('time_range1', models.DateTimeField(blank=True, null=True)),
                ('time_range2', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gift_code',
                'verbose_name': '\u793c\u54c1\u7801',
                'verbose_name_plural': '\u793c\u54c1\u7801',
            },
        ),
        migrations.CreateModel(
            name='GiftCodeUsingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_id', models.IntegerField(db_index=True)),
                ('gift_code', models.CharField(db_index=True, max_length=255)),
                ('using_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gift_code_using_log',
                'verbose_name': '\u793c\u54c1\u7801\u4f7f\u7528\u8bb0\u5f55',
                'verbose_name_plural': '\u793c\u54c1\u7801\u4f7f\u7528\u8bb0\u5f55',
            },
        ),
    ]
