# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_code', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcode',
            name='mail_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='giftcode',
            name='mail_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
