# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-03 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('server_id', models.IntegerField(db_index=True)),
                ('char_id', models.IntegerField(db_index=True)),
                ('goods_id', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fee', models.IntegerField(default=0)),
                ('channel_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('ssid', models.CharField(blank=True, max_length=255)),
                ('unique_trade_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('return_code', models.IntegerField(default=0)),
                ('complete_timestamp', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'db_table': 'purchase',
                'verbose_name': '\u5145\u503c',
                'verbose_name_plural': '\u5145\u503c',
            },
        ),
    ]
