# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-11 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase1SDK',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ct', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('pt', models.IntegerField()),
                ('sdk', models.CharField(db_index=True, max_length=255)),
                ('ssid', models.CharField(max_length=255)),
                ('st', models.IntegerField()),
                ('tcd', models.CharField(max_length=255, unique=True)),
                ('uid', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'purchase_1sdk',
                'verbose_name': '\u5145\u503c-1sdk',
                'verbose_name_plural': '\u5145\u503c-1sdk',
            },
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='channel_id',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='complete_timestamp',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='return_code',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='ssid',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='unique_trade_id',
        ),
        migrations.AddField(
            model_name='purchase',
            name='complete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='platform',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
