# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-12 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20160811_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase1sdk',
            name='ct',
            field=models.IntegerField(db_index=True),
        ),
    ]
