# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_auto_20160812_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseIOS',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, max_length=255)),
                ('product_id', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('status', models.IntegerField()),
                ('environment', models.CharField(max_length=255)),
                ('application_version', models.CharField(db_index=True, max_length=255)),
                ('receipt_data', models.TextField()),
            ],
            options={
                'db_table': 'purchase_ios',
                'verbose_name': '\u5145\u503c-IOS',
                'verbose_name_plural': '\u5145\u503c-IOS',
            },
        ),
        migrations.AlterField(
            model_name='purchase',
            name='platform',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
