# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_auto_20161101_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseStarsCloud',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('channOrderId', models.CharField(max_length=255)),
                ('channType', models.CharField(max_length=255)),
                ('pmOrderId', models.CharField(max_length=255, unique=True)),
                ('uid', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'purchase_stars_cloud',
                'verbose_name': '\u5145\u503c-Stars-Cloud',
                'verbose_name_plural': '\u5145\u503c-Stars-Cloud',
            },
        ),
    ]
